name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for version update
        run: |
          echo "Waiting for version update..."
          sleep 10  # Short delay to prevent race conditions
          LATEST_COMMIT=$(git rev-parse HEAD)
          
          while true; do
              git fetch origin master
              REMOTE_COMMIT=$(git rev-parse origin/master)

              if [ "$LATEST_COMMIT" != "$REMOTE_COMMIT" ]; then
                  echo "New update detected, pulling changes..."
                  git pull origin master
                  break
              fi

              echo "Waiting for the update..."
              sleep 5
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/rambot/

    steps:
      - name: Download release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
